### ISSUE TITLE
When debug start

### ISSUE THREAD

**Issue by dani80vdt** [Microsoft/WindowsUIDevLabs#155]
Cannot create instance of type 'SamplesCommon.BackDrop' [Line: 25 Position: 53]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at CompositionSampleGallery.MainPage.InitializeComponent()
   at CompositionSampleGallery.MainPage..ctor(Rect imageBounds)
   at CompositionSampleGallery.ExtendedSplashScree

**Comment by msftdavid** [comment]
Sorry for the late response. In what context are you running into this error? It seems like you're trying to the BackDrop control in SamplesCommon.. Is this a message from simply running the Sample Gallery or is it from your own app?

**Comment by msftdavid** [comment]
Closing issue due to inactivity.
